"""initial schema

Revision ID: 98443895b9f5
Revises: 
Create Date: 2026-07-13 09:56:34.874252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98443895b9f5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calls',
    sa.Column('call_id', sa.String(), nullable=False),
    sa.Column('processed_at', sa.String(), nullable=False),
    sa.Column('labeled_transcript', sa.String(), nullable=False),
    sa.Column('dead_air_total_seconds', sa.Float(), nullable=False),
    sa.Column('diarization_warning', sa.String(), nullable=True),
    sa.Column('composite_score', sa.Integer(), nullable=False),
    sa.Column('max_possible', sa.Integer(), nullable=False),
    sa.Column('critical_failure', sa.Boolean(), nullable=False),
    sa.Column('fraud_flags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('claims_checked', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('call_id')
    )
    op.create_table('call_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.String(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('start', sa.Float(), nullable=False),
    sa.Column('end', sa.Float(), nullable=False),
    sa.Column('speaker', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.call_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dead_air_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.String(), nullable=False),
    sa.Column('start', sa.Float(), nullable=False),
    sa.Column('end', sa.Float(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.call_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dimension_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.String(), nullable=False),
    sa.Column('dimension_key', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('reasoning', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.call_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fact_check_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.String(), nullable=False),
    sa.Column('claim', sa.String(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('explanation', sa.String(), nullable=False),
    sa.Column('kb_fact', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.call_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fact_check_results')
    op.drop_table('dimension_scores')
    op.drop_table('dead_air_instances')
    op.drop_table('call_segments')
    op.drop_table('calls')
    # ### end Alembic commands ###
